CREATE OR REPLACE PROCEDURE SP_CREAR_DETALLE_SUBASTA (
IN_TRANSPORTISTA_ID IN NUMBER,
IN_SUBASTA_ID IN NUMBER,
IN_VALOR_PROPUESTA IN NUMBER,
OUT_GLOSA 		OUT VARCHAR2,
OUT_ESTADO 		OUT NUMBER
--OUT_ID_SALIDA 	OUT NUMBER
)AS 
BEGIN

INSERT INTO FERIA2.detalle_subasta (
TRANSPORTISTA_ID,
SUBASTA_ID,
VALORPROPUESTA
) VALUES (
IN_TRANSPORTISTA_ID,
IN_SUBASTA_ID,
IN_VALOR_PROPUESTA
);

--RETURNING ID INTO OUT_ID_SALIDA;

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := feria2.FN_GET_GLOSA_ERROR;
  NULL;
END SP_CREAR_DETALLE_SUBASTA;
