create or replace PROCEDURE SP_CLIENTE_CREAR (

	IN_USUARIO_ID IN NUMBER,
	IN_IDENTIFICADOR IN VARCHAR2,
	IN_RAZON_SOCIAL IN VARCHAR2,
	IN_DIRECCION IN VARCHAR2,
	IN_CIUDAD in VARCHAR2,
	IN_PAIS_ORIGEN IN VARCHAR2,
	IN_TIPO_CLIENTE IN NUMBER,
	IN_CORREO IN VARCHAR2,

	OUT_GLOSA 		OUT VARCHAR2,
	OUT_ESTADO 		OUT NUMBER,
	OUT_ID_SALIDA 	OUT NUMBER
	
) AS 
BEGIN

    OUT_GLOSA := 'SP_CLIENTE_CREAR ejecutado exitosamente';
    OUT_ESTADO := 0;

	INSERT INTO CLIENTE (
		ID,
		USUARIO_ID,
		IDENTIFICADOR,
		RAZONSOCIAL,
		DIRECCION,
		CIUDAD,
		PAIS_ORIGEN,
		TIPO_CLIENTE,
		CORREO,
		HABILITADO
	) 
	VALUES(
		CLIENTE_SEQUENCE.nextval,
		IN_USUARIO_ID,
		IN_IDENTIFICADOR,
		IN_RAZON_SOCIAL,
		IN_DIRECCION,
		IN_CIUDAD,
		IN_PAIS_ORIGEN,
		IN_TIPO_CLIENTE,
		IN_CORREO,
		1
	)
RETURNING ID INTO OUT_ID_SALIDA;

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := FN_GET_GLOSA_ERROR;

NULL;
END SP_CLIENTE_CREAR;
