create or replace PROCEDURE SP_CREAR_DETALLE_SOLICITUD (

IN_SOLICITUD_COMPRA_ID IN NUMBER,
IN_PRODUCTO IN VARCHAR2,
IN_KILOGRAMOS IN VARCHAR2,
OUT_GLOSA 		OUT VARCHAR2,
OUT_ESTADO 		OUT NUMBER,
OUT_ID_SALIDA 	OUT NUMBER
) AS 
BEGIN

INSERT INTO detalle_solicitud (
ID,
SOLICITUD_COMPRA_ID,
PRODUCTO,
KILOGRAMOS
) 
VALUES(
DETALLE_SOLICITUD_SEQUENCE.NEXTVAL,
IN_SOLICITUD_COMPRA_ID,
IN_PRODUCTO,
IN_KILOGRAMOS
)
RETURNING ID INTO OUT_ID_SALIDA;

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := FN_GET_GLOSA_ERROR;

NULL;
END SP_CREAR_DETALLE_SOLICITUD;
