CREATE OR REPLACE PROCEDURE SP_CREAR_CONTRATO (
IN_PRODUCTOR_ID IN VARCHAR2,
IN_FECHA_INICIO DATE,
IN_FECHA_TERMINO DATE,
IN_FECHA_CREACION DATE,
IN_VIGENCIA CHAR,
OUT_GLOSA 		OUT VARCHAR2,
OUT_ESTADO 		OUT NUMBER,
OUT_ID_SALIDA 	OUT NUMBER
)AS 
BEGIN

INSERT INTO contrato (
ID,
FECHAINICIO,
FECHATERMINO,
FECHACREACION,
vigencia
) 
VALUES (
CONTRATO_SEQUENCE.NEXTVAL,
IN_FECHA_INICIO,
IN_FECHA_TERMINO,
SYSDATE,
IN_VIGENCIA
)

RETURNING ID INTO OUT_ID_SALIDA;

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := FN_GET_GLOSA_ERROR;
  NULL;
END SP_CREAR_CONTRATO;
