CREATE OR REPLACE PROCEDURE SP_CONTRATO_CREAR (

    IN_FECHA_INICIO     IN DATE,
    IN_FECHA_TERMINO    IN DATE,
    IN_FECHA_CREACION   IN DATE,
    IN_VIGENCIA         IN CHAR,
    
    OUT_GLOSA 		OUT VARCHAR2,
    OUT_ESTADO 		OUT NUMBER,
    OUT_ID_SALIDA 	OUT NUMBER
    
)AS 
BEGIN

    OUT_GLOSA := 'SP_CONTRATO_CREAR ejecutado exitosamente';
    OUT_ESTADO := 0;

    INSERT INTO contrato (
        ID,
        FECHAINICIO,
        FECHATERMINO,
        FECHACREACION,
        vigencia
    ) 
    VALUES (
        CONTRATO_SEQUENCE.NEXTVAL,
        IN_FECHA_INICIO,
        IN_FECHA_TERMINO,
        IN_FECHA_CREACION,
        IN_VIGENCIA
    )

RETURNING ID INTO OUT_ID_SALIDA;

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := FN_GET_GLOSA_ERROR;
    NULL;
END SP_CONTRATO_CREAR;
