create or replace PROCEDURE SP_CREAR_STOCK_DISPONIBLE (
IN_PRODUCTO_ID IN NUMBER,
IN_KILOGRAMOS IN NUMBER,
IN_FECHAULIOMAMODIFICACION IN DATE,
OUT_GLOSA 		OUT VARCHAR2,
OUT_ESTADO 		OUT NUMBER,
OUT_ID_SALIDA 	OUT NUMBER
)AS 
BEGIN

INSERT INTO stock_disponible (
ID,
PRODUCTO_ID,
KILOGRAMOS,
FECHAULTIMAMODIFICACION
) VALUES (
STOCK_DISPONIBLE_SEQUENCE.NEXTVAL,
IN_PRODUCTO_ID,
IN_KILOGRAMOS,
IN_FECHAULIOMAMODIFICACION
)

RETURNING ID INTO OUT_ID_SALIDA;

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := FN_GET_GLOSA_ERROR;
  NULL;
END SP_CREAR_STOCK_DISPONIBLE;
