create or replace PROCEDURE SP_ROL_CONSULTAR_ID(
  IN_ID  	        IN NUMBER,
  OUT_RESULTADO 	OUT SYS_REFCURSOR
) AS
     
      
BEGIN


    OPEN OUT_RESULTADO FOR
        SELECT ID, DESCRIPCION, AREA
        FROM ROL
        WHERE ID = IN_ID; 


END SP_ROL_CONSULTAR_ID;