CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_SUBASTA (
IN_ID_SUBASTA IN NUMBER,
IN_FECHATERMINO IN DATE,
IN_PRECIO_GANADOR IN NUMBER,
IN_HABILITADO IN NUMBER,
OUT_GLOSA 		OUT VARCHAR2,
OUT_ESTADO 		OUT NUMBER
) AS 
BEGIN

UPDATE FERIA2.subasta SET fechatermino=IN_FECHATERMINO,precioganador=IN_PRECIO_GANADOR, habilitado=IN_HABILITADO WHERE ID=IN_ID_SUBASTA;

EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := feria2.FN_GET_GLOSA_ERROR;
  NULL;
END SP_ACTUALIZAR_SUBASTA;
