CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_DETALLESOLICITUD (
IN_ID_DETALLE_SOLICITUD IN NUMBER,
IN_PRODUCTO IN VARCHAR2,
IN_KILOGRAMOS IN NUMBER,
OUT_GLOSA 	OUT VARCHAR2,
OUT_ESTADO 	OUT NUMBER
)AS 
BEGIN

UPDATE FERIA2.detalle_solicitud SET producto=IN_PRODUCTO, KILOGRAMOS=IN_KILOGRAMOS WHERE ID=IN_ID_DETALLE_SOLICITUD;

EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := feria2.FN_GET_GLOSA_ERROR;
  NULL;
END SP_ACTUALIZAR_DETALLESOLICITUD;
