CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_CONTRATO (
IN_ID_CONTRATO IN VARCHAR2,
IN_FECHA_INICIO DATE,
IN_FECHA_TERMINO DATE,
IN_VIGENCIA CHAR,
OUT_GLOSA 		OUT VARCHAR2,
OUT_ESTADO 		OUT NUMBER,
OUT_ID_SALIDA 	OUT NUMBER
)AS 
BEGIN

UPDATE feria2.CONTRATO SET fechainicio=IN_FECHA_INICIO, fechatermino=IN_FECHA_TERMINO, fechacreacion= SYSDATE, VIGENCIA=IN_VIGENCIA WHERE ID=IN_ID_CONTRATO;

EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := feria2.FN_GET_GLOSA_ERROR;
  NULL;
END SP_ACTUALIZAR_CONTRATO;
