CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_PRODUCTOR (

IN_ID_PRODUCTOR IN NUMBER,
IN_CONTRATO_ID IN NUMBER,
IN_RUT IN VARCHAR2,
IN_RAZONSOCIAL IN VARCHAR2,
IN_DIRECCION IN VARCHAR2,
IN_COMUNA IN VARCHAR2,
IN_CORREO IN VARCHAR2,
IN_HABILITADO IN NUMBER,
IN_USUARIO_ID IN NUMBER,

OUT_GLOSA 	OUT VARCHAR2,
OUT_ESTADO 	OUT NUMBER)AS 
BEGIN

    OUT_GLOSA := 'SP_ACTUALIZAR_USUARIO ejecutado exitosamente';
    OUT_ESTADO := 0;
    
    UPDATE PRODUCTOR 
    SET 
    PRODUCTOR.CONTRATO_ID=IN_CONTRATO_ID,
    PRODUCTOR.RUT=IN_RUT,
    PRODUCTOR.RAZONSOCIAL=IN_RAZONSOCIAL,
    PRODUCTOR.DIRECCION=IN_DIRECCION,
    PRODUCTOR.COMUNA=IN_COMUNA,
    PRODUCTOR.CORREO=IN_CORREO,
    PRODUCTOR.HABILITADO=IN_HABILITADO
    WHERE ID=IN_ID_PRODUCTOR ;
    
      
    MERGE INTO usuario usu
    USING ( SELECT * from productor) pro
    ON (usu.id=pro.usuario_id)
    WHEN MATCHED THEN
    UPDATE SET
      usu.correo=pro.correo;
    
    
    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := FN_GET_GLOSA_ERROR;

END SP_ACTUALIZAR_PRODUCTOR;
