CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_STOCK (
IN_ID_STOCK IN NUMBER,
IN_KILOGRAMOS IN VARCHAR2,
IN_FECHA_ULTIMA_MODIFICACION IN DATE,
OUT_GLOSA 		OUT VARCHAR2,
OUT_ESTADO 		OUT NUMBER
) AS 
BEGIN

UPDATE stock_disponible SET KILOGRAMOS=IN_KILOGRAMOS, fechaultimamodificacion=IN_FECHA_ULTIMA_MODIFICACION WHERE id=IN_ID_STOCK;

EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := FN_GET_GLOSA_ERROR;

  NULL;
END SP_ACTUALIZAR_STOCK;
