CREATE OR REPLACE PROCEDURE SP_DETALLE_SUBASTA_CREAR (

	IN_TRANSPORTISTA_ID 	IN NUMBER,
	IN_SUBASTA_ID 			IN NUMBER,
	IN_VALOR_PROPUESTA 		IN NUMBER,

	OUT_GLOSA 				OUT VARCHAR2,
	OUT_ESTADO 				OUT NUMBER,
	OUT_ID_SALIDA 			OUT NUMBER
)AS 
BEGIN
	
	OUT_GLOSA := 'SP_DETALLE_SUBASTA_CREAR ejecutado exitosamente';
    OUT_ESTADO := 0;

	INSERT INTO DETALLE_SUBASTA (
			TRANSPORTISTA_ID,
			SUBASTA_ID,
			VALORPROPUESTA
	) VALUES (
			IN_TRANSPORTISTA_ID,
			IN_SUBASTA_ID,
			IN_VALOR_PROPUESTA
	);

	OUT_ID_SALIDA := 0;

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := FN_GET_GLOSA_ERROR;
  NULL;
END SP_DETALLE_SUBASTA_CREAR;
