create or replace PROCEDURE SP_DETALLE_SUBASTA_CONSULTAR
(
    -- Opcionales
    IN_TRANSPORTISTA_ID     IN NUMBER,
    IN_SUBASTA_ID         	IN NUMBER,
    IN_VALORPROPUESTA       IN NUMBER,

    out_resultado           OUT SYS_REFCURSOR
)
AS

BEGIN

    OPEN out_resultado FOR


    select  TRANSPORTISTA_ID,
            SUBASTA_ID ,
            VALORPROPUESTA
    FROM DETALLE_SUBASTA
    where 	
    		-- Opcionales
    		    (IN_TRANSPORTISTA_ID IS NULL OR TRANSPORTISTA_ID = IN_TRANSPORTISTA_ID)
			AND (IN_SUBASTA_ID IS NULL OR SUBASTA_ID = IN_SUBASTA_ID)
			AND (IN_VALORPROPUESTA IS NULL OR VALORPROPUESTA = IN_VALORPROPUESTA)
    ;

EXCEPTION


    WHEN OTHERS THEN
		out_resultado := null;

END SP_DETALLE_SUBASTA_CONSULTAR;
