create or replace PROCEDURE SP_INGRESO_CREAR (


		IN_PRODUCTOR_ID 				IN NUMBER,
		IN_PRODUCTO_ID 					IN NUMBER,
		IN_KILOGRAMOS 					IN NUMBER,
		IN_PRECIO_KG_COSTO_UNITARIO 	IN NUMBER,

		OUT_GLOSA 		OUT VARCHAR2,
		OUT_ESTADO 		OUT NUMBER,
		OUT_ID_SALIDA 	OUT NUMBER

) AS

ID_PARAMETRO_PORC_AUMENTO	NUMBER := 1;
VALOR_PARAMETRO     		NUMBER := 0;


BEGIN

	SELECT VALOR
    INTO VALOR_PARAMETRO
    FROM PARAMETROS param
    WHERE param.ID = ID_PARAMETRO_PORC_AUMENTO;
    
    OUT_GLOSA := 'SP_INGRESO_CREAR ejecutado exitosamente';
    OUT_ESTADO := 0;


	INSERT INTO INGRESO (
		ID,
		PRODUCTOR_ID,
		PRODUCTO_ID,
		FECHACREACION,
		KILOGRAMOS,
		PRECIOKGCOSTOUNITARIO,
		PRECIOKGVENTAUNITARIO,
		HABILITADO
	) VALUES (
		INGRESO_SEQUENCE.NEXTVAL,
		IN_PRODUCTOR_ID,
		IN_PRODUCTO_ID,
		SYSDATE,
		IN_KILOGRAMOS,
		IN_PRECIO_KG_COSTO_UNITARIO,
		ROUND(IN_PRECIO_KG_COSTO_UNITARIO + ((IN_PRECIO_KG_COSTO_UNITARIO * VALOR_PARAMETRO ) / 100 )),
		1
	)

	RETURNING ID INTO OUT_ID_SALIDA;


    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := FN_GET_GLOSA_ERROR;
  NULL;
END SP_INGRESO_CREAR;