create or replace PROCEDURE SP_SUBASTA_CREAR (

	IN_FECHATERMINO IN DATE,


	OUT_GLOSA 		OUT VARCHAR2,
	OUT_ESTADO 		OUT NUMBER,
	OUT_ID_SALIDA 	OUT NUMBER)

AS 
BEGIN

	OUT_GLOSA := 'SP_SUBASTA_CREAR ejecutado exitosamente';
    OUT_ESTADO := 0;

	INSERT INTO SUBASTA (
		ID,
		FECHATERMINO,
		PRECIOGANADOR,
		HABILITADO
	) 
	VALUES (
		SUBASTA_SEQUENCE.NEXTVAL,
		IN_FECHATERMINO,
		0,
		1
	)

	RETURNING ID INTO OUT_ID_SALIDA;

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := FN_GET_GLOSA_ERROR;
  NULL;
END SP_SUBASTA_CREAR;
