CREATE OR REPLACE PROCEDURE SP_SUBASTA_ACTUALIZAR (

	IN_ID_SUBASTA 		IN NUMBER,
	IN_FECHATERMINO 	IN DATE,
	IN_PRECIO_GANADOR 	IN NUMBER,
	IN_HABILITADO 		IN NUMBER,


	OUT_GLOSA 		        OUT VARCHAR2,
    OUT_ESTADO 		        OUT NUMBER,
    OUT_ID_SALIDA 	        OUT NUMBER

) AS

EX_Sin_data     EXCEPTION;
tiene_datos     NUMBER := 0;

BEGIN

	OUT_GLOSA := 'SP_SUBASTA_ACTUALIZAR ejecutado exitosamente';
    OUT_ESTADO := 0;

	SELECT
        COUNT(1)
    INTO tiene_datos
    FROM SUBASTA subasta
    WHERE subasta.ID = IN_ID_SUBASTA;

    IF tiene_datos = 0 THEN
        RAISE EX_Sin_data;
    END IF;


	UPDATE SUBASTA 
	SET
       SUBASTA.FECHATERMINO = NVL2( IN_FECHATERMINO , IN_FECHATERMINO, SUBASTA.FECHATERMINO),
       SUBASTA.PRECIOGANADOR = NVL2( IN_PRECIO_GANADOR , IN_PRECIO_GANADOR, SUBASTA.PRECIOGANADOR),
       SUBASTA.HABILITADO = NVL2( IN_HABILITADO , IN_HABILITADO, SUBASTA.HABILITADO)
	WHERE ID=IN_ID_SUBASTA;

	OUT_ID_SALIDA := IN_ID_SUBASTA;

EXCEPTION
        WHEN EX_Sin_data THEN
            OUT_GLOSA := 'SP_SUBASTA_ACTUALIZAR no se encuentra id';
            OUT_ESTADO := -1;
            OUT_ID_SALIDA := -1;


        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := FN_GET_GLOSA_ERROR;

        NULL;
END SP_SUBASTA_ACTUALIZAR;
