CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_INGRESO (
IN_ID_INGRESO IN NUMBER,
IN_PRODUCTOR_ID IN NUMBER,
IN_PRODUCTO_ID IN NUMBER,
--IN_FECHA_CREACION IN DATE,
IN_KILOGRAMOS IN NUMBER,
IN_PRECIO_KG_COSTO_UNITARIO IN NUMBER,
IN_PRECIO_KG_VENTA_UNITARIO IN NUMBER,
OUT_GLOSA 		OUT VARCHAR2,
OUT_ESTADO 		OUT NUMBER
) AS 
BEGIN

UPDATE INGRESO SET fechacreacion=SYSDATE, KILOGRAMOS=IN_KILOGRAMOS, PRECIOKGCOSTOUNITARIO=IN_PRECIO_KG_COSTO_UNITARIO, PRECIOKGVENTAUNITARIO = IN_PRECIO_KG_VENTA_UNITARIO WHERE ID=IN_ID_INGRESO;


    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := feria2.FN_GET_GLOSA_ERROR;
  NULL;
END SP_ACTUALIZAR_INGRESO;
