
--Cliente

CREATE SEQUENCE CLIENTE_SEQUENCE
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIGGER_CLIENTE
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
SELECT CLIENTE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--Contrato

CREATE SEQUENCE CONTRATO_SEQUENCE
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIGGER_CONTRATO
BEFORE INSERT ON CONTRATO
FOR EACH ROW
BEGIN
SELECT CONTRATO_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--Detalle_solicitud

CREATE SEQUENCE DETALLE_SOLICITUD_SEQUENCE
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIGGER_DETALLE_SOLICITUD
BEFORE INSERT ON DETALLE_SOLICITUD
FOR EACH ROW
BEGIN
SELECT DETALLE_SOLICITUD_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--Ingreso

CREATE SEQUENCE INGRESO_SEQUENCE
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIGGER_INGRESO
BEFORE INSERT ON INGRESO
FOR EACH ROW
BEGIN
SELECT INGRESO_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--Proceso_venta

CREATE SEQUENCE PROCESO_VENTA_SEQUENCE
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIGGER_PROCESO_VENTA
BEFORE INSERT ON PROCESO_VENTA
FOR EACH ROW
BEGIN
SELECT PROCESO_VENTA_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--Producto

CREATE SEQUENCE PRODUCTO_SEQUENCE
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIGGER_PRODUCTO
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
SELECT PRODUCTO_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--Productor

CREATE SEQUENCE PRODUCTOR_SEQUENCE
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIGGER_PRODUCTOR
BEFORE INSERT ON PRODUCTOR
FOR EACH ROW
BEGIN
SELECT PRODUCTOR_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--Rol

CREATE SEQUENCE ROL_SEQUENCE
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIGGER_ROL
BEFORE INSERT ON ROL
FOR EACH ROW
BEGIN
SELECT ROL_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

