CREATE OR REPLACE PROCEDURE SP_ELIMINAR_TRANSPORTISTA (
IN_ID_TRANSPORTISTA IN NUMBER,
OUT_GLOSA 	OUT VARCHAR2,
OUT_ESTADO 	OUT NUMBER
) AS 
BEGIN

UPDATE FERIA2.transportista SET HABILITADO=0 WHERE ID=IN_ID_TRANSPORTISTA;

EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := feria2.FN_GET_GLOSA_ERROR;

  NULL;
END SP_ELIMINAR_TRANSPORTISTA;
