create or replace PROCEDURE SP_ELIMINAR_USUARIO(
  
IN_ID_USUARIO 	IN NUMBER,

OUT_GLOSA 	OUT VARCHAR2,
OUT_ESTADO 	OUT NUMBER
) AS


BEGIN

    OUT_GLOSA := 'SP_ELIMINAR_USUARIO ejecutado exitosamente';
    OUT_ESTADO := 0;
 
   UPDATE USUARIO SET habilitado=0 WHERE ID=IN_ID_USUARIO ;
   
    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := FN_GET_GLOSA_ERROR;
END SP_ELIMINAR_USUARIO;